server:
  port: 9090

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf8&serverTimezone=UTC


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id #全局设置雪花算法
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
